import type { Stats } from "./types";

// ---------------------------------------------------------------------------
// Random "Easter egg" events. Every so often after an action, life throws a
// surprise — a windfall (found wallet, lottery, inheritance) or, now and then,
// a setback. They pop up, apply their effects, and get woven into your life
// story. Add one by dropping an entry in EVENTS.
// ---------------------------------------------------------------------------

export interface RandomEvent {
  id: string;
  emoji: string;
  title: string;
  desc: string;
  /** Big flashy money figure shown in the popup (flavour). */
  cash?: string;
  effects: Partial<Stats>;
  /** Relative frequency (higher = more common). */
  weight: number;
  /** Can only ever happen once per life. */
  once?: boolean;
  minAge?: number;
  maxAge?: number;
  /** false = a setback (styled differently). Defaults to true. */
  good?: boolean;
  /** Short clause for the life story's "twists of fate" line. */
  storyClause: string;
}

export const EVENTS: RandomEvent[] = [
  {
    id: "wallet",
    emoji: "👛",
    title: "Lucky find!",
    desc: "You spotted a fat wallet on the street and handed it in — the grateful owner let you keep a $100,000 reward!",
    cash: "+ $100,000",
    effects: { wealth: 12, happiness: 4 },
    weight: 5,
    minAge: 8,
    storyClause: "found a wallet and pocketed a handsome reward",
  },
  {
    id: "lottery",
    emoji: "🎟️",
    title: "JACKPOT!!",
    desc: "On a whim you bought a lottery ticket — and hit the jackpot for $500,000!",
    cash: "+ $500,000",
    effects: { wealth: 35, happiness: 10 },
    weight: 1,
    once: true,
    minAge: 18,
    storyClause: "won half a million on a lottery ticket",
  },
  {
    id: "inherit",
    emoji: "📜",
    title: "An inheritance",
    desc: "A distant relative remembered you fondly and left you a tidy inheritance.",
    cash: "+ $250,000",
    effects: { wealth: 20, happiness: 3 },
    weight: 2,
    once: true,
    minAge: 25,
    storyClause: "inherited a small fortune from family",
  },
  {
    id: "bonus",
    emoji: "🎉",
    title: "Surprise bonus",
    desc: "Your hard work paid off with an unexpected bonus.",
    cash: "+ $8,000",
    effects: { wealth: 7, happiness: 3 },
    weight: 4,
    minAge: 22,
    storyClause: "landed a surprise bonus at work",
  },
  {
    id: "puppy",
    emoji: "🐶",
    title: "A new friend",
    desc: "A stray puppy followed you home. Who could say no to that face?",
    effects: { happiness: 9, health: 2 },
    weight: 4,
    minAge: 5,
    storyClause: "adopted a stray puppy who adored you",
  },
  {
    id: "viral",
    emoji: "🌟",
    title: "You went viral!",
    desc: "Something you posted blew up online overnight — a little fame and fortune.",
    cash: "+ $15,000",
    effects: { wealth: 8, happiness: 6 },
    weight: 3,
    minAge: 12,
    storyClause: "had a moment of internet fame",
  },
  {
    id: "loan",
    emoji: "🤝",
    title: "Paid back!",
    desc: "An old friend finally repaid a loan you'd written off years ago.",
    cash: "+ $20,000",
    effects: { wealth: 9, happiness: 2 },
    weight: 3,
    minAge: 20,
    storyClause: "got back money from a long-forgotten loan",
  },
  {
    id: "contest",
    emoji: "🏆",
    title: "You won a contest!",
    desc: "You entered a contest just for fun — and actually won!",
    cash: "+ $5,000",
    effects: { wealth: 5, happiness: 7 },
    weight: 3,
    minAge: 8,
    storyClause: "won a contest you entered on a whim",
  },
  {
    id: "scholarship",
    emoji: "🎓",
    title: "Scholarship!",
    desc: "Your grades earned you a surprise scholarship.",
    cash: "+ $30,000",
    effects: { wealth: 10, smarts: 4, happiness: 5 },
    weight: 2,
    minAge: 14,
    maxAge: 24,
    storyClause: "earned a surprise scholarship",
  },
  {
    id: "gymfree",
    emoji: "🎁",
    title: "Free membership",
    desc: "You won a whole year of free gym membership. Time to get moving!",
    effects: { health: 8, happiness: 3 },
    weight: 3,
    minAge: 14,
    storyClause: "won a year of free gym membership",
  },
  {
    id: "promo",
    emoji: "📈",
    title: "Promotion!",
    desc: "Your boss pulled you aside — you're being promoted, with a raise to match.",
    cash: "+ $40,000 / yr",
    effects: { wealth: 11, happiness: 6 },
    weight: 3,
    minAge: 24,
    storyClause: "earned a well-deserved promotion",
  },
  {
    id: "dividend",
    emoji: "🏦",
    title: "Dividend day",
    desc: "A stock you forgot you owned paid out a tidy dividend.",
    cash: "+ $6,000",
    effects: { wealth: 6, happiness: 2 },
    weight: 3,
    minAge: 22,
    storyClause: "collected a surprise dividend",
  },
  {
    id: "gameshow",
    emoji: "📺",
    title: "TV game show!",
    desc: "You went on a quiz show and your smarts won you the grand prize!",
    cash: "+ $120,000",
    effects: { wealth: 14, happiness: 9, smarts: 2 },
    weight: 1,
    once: true,
    minAge: 18,
    storyClause: "won big on a TV quiz show",
  },
  {
    id: "gift",
    emoji: "🎁",
    title: "A generous gift",
    desc: "Your grandparents slipped you a fat envelope 'just because'.",
    cash: "+ $5,000",
    effects: { wealth: 5, happiness: 5 },
    weight: 3,
    minAge: 6,
    maxAge: 30,
    storyClause: "received a generous gift from family",
  },
  {
    id: "refund",
    emoji: "🧾",
    title: "Tax refund",
    desc: "The taxman owed YOU for once — a welcome refund landed.",
    cash: "+ $3,500",
    effects: { wealth: 4 },
    weight: 4,
    minAge: 22,
    storyClause: "got a cheering tax refund",
  },
  {
    id: "crypto",
    emoji: "🪙",
    title: "Early bet pays off",
    desc: "A tiny punt on a new coin years ago suddenly mooned. You cashed out in time!",
    cash: "+ $200,000",
    effects: { wealth: 22, happiness: 8 },
    weight: 1,
    once: true,
    minAge: 18,
    storyClause: "struck gold on an early crypto bet",
  },
  {
    id: "busk",
    emoji: "🎸",
    title: "Street talent",
    desc: "You played a few songs on the corner and a crowd showered you with notes.",
    cash: "+ $1,200",
    effects: { wealth: 3, happiness: 5, fun: 3 },
    weight: 3,
    minAge: 12,
    storyClause: "made a happy crowd (and a few bucks) busking",
  },
  // --- the occasional setback, to keep luck honest ---
  {
    id: "scam",
    emoji: "⚠️",
    title: "Scammed!",
    desc: "A too-good-to-be-true investment turned out to be a scam. Ouch.",
    cash: "− $40,000",
    effects: { wealth: -10, happiness: -5 },
    weight: 2,
    minAge: 25,
    good: false,
    storyClause: "lost money to a clever scammer",
  },
  {
    id: "medbill",
    emoji: "🏥",
    title: "Surprise bill",
    desc: "An unexpected medical bill landed on your doormat.",
    cash: "− $10,000",
    effects: { wealth: -7, health: -3 },
    weight: 2,
    minAge: 30,
    good: false,
    storyClause: "got hit with a surprise medical bill",
  },
  {
    id: "phone",
    emoji: "💥",
    title: "Cracked screen",
    desc: "You dropped your phone on the pavement. A small but annoying expense.",
    cash: "− $500",
    effects: { wealth: -3, happiness: -2 },
    weight: 2,
    minAge: 12,
    good: false,
    storyClause: "smashed a phone screen at the worst moment",
  },
  {
    id: "carrepair",
    emoji: "🔧",
    title: "It's the gearbox…",
    desc: "Your car broke down and the repair bill made your eyes water.",
    cash: "− $3,000",
    effects: { wealth: -6, happiness: -3 },
    weight: 2,
    minAge: 18,
    good: false,
    storyClause: "got stung by a brutal car repair bill",
  },
  {
    id: "crash",
    emoji: "📉",
    title: "Market crash",
    desc: "The markets tumbled and took a chunk of your savings with them.",
    cash: "− $80,000",
    effects: { wealth: -12, happiness: -5 },
    weight: 2,
    once: true,
    minAge: 28,
    good: false,
    storyClause: "rode out a nasty market crash",
  },
  {
    id: "theft",
    emoji: "🥷",
    title: "Pickpocketed!",
    desc: "Someone lifted your wallet in a crowd. Cancel the cards…",
    cash: "− $2,000",
    effects: { wealth: -4, happiness: -3 },
    weight: 2,
    minAge: 14,
    good: false,
    storyClause: "got pickpocketed in a busy crowd",
  },
];
